name: Zip 

on:
  push:
    

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: qfield-3d-nav/
          dest: plugin.zip
      - uses: actions/upload-artifact@v1.1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
