name: Zip 

on:
  push:
    

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: qfield-3d-nav/
          dest: plugin.zip
